### ISSUE TITLE
Persistent settings

### ISSUE THREAD

**Issue by DannyBen** [rocker-org/rocker#263]
I have spent some time [on the wiki](https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine) and other documentation I could find here, to try and figure out where are all the RStudio settings stored in the container, so that I can mount that folder to my host, and have persistent settings.

Can you share this information? Or add it to the above linked document?

EDIT:

I have managed to guess this partially, and I am mounting `/home/rstudio/.rstudio` and `/home/rstudio/.config`. After mounting like this, the settings are saved, but I am getting an error message "the previous session was terminated abnormally". Not sure why.

**Comment by DannyBen** [comment]
I figured it out, I am mounting the entire `/home/rstudio` directory to the host. Maybe this should be mentioned somewhere, that this is the way to persist the container's settings? I would remove the "docker commit" portion of the instructions, it is not the best practice.

I am using this `docker-compose` to get all the services I need from this image:

```yaml
version: '3'

services:
  bash: &default
    image: rocker/rstudio
    command: bash
    volumes: 
    - ./home:/home/rstudio

  console:
    <<: *default
    command: /usr/local/bin/R

  web:
    <<: *default
    command: /init
    ports: ["3000:8787"]
```
