### ISSUE TITLE
Docker containers of all image versions are infinity restarting if pulling with docker compose

### ISSUE THREAD

**Issue by vartagg** [rocker-org/rocker#272]
Example of docker-compose.yml

```
r:
  restart: always
  image: rocker/r-ver:latest

```

**Comment by eddelbuettel** [comment]
Random guess:  Maybe it needs the equivalent of `docker run -ti` there, ie declare interactive and terminal mode?

**Comment by vartagg** [comment]
@eddelbuettel Thanks a lot! I am very beginning with Docker and didn't know about these options. As you said, I changed docker-compose.yml

```
r:
  build: r
  restart: always
  stdin_open: true
  tty: true

```
