### ISSUE TITLE
Environmental variables not accessible inside R terminal

### ISSUE THREAD

**Issue by raubreywhite** [rocker-org/rocker#347]
My docker-compose file looks like this:

```
services:
  rstudio:
    image: rocker/verse:3.6.0
    volumes:
      - $GIT:/git
      - $DASHBOARDS_GIT:/dashboards/

      - $DASHBOARDS_CONFIG:/config/
      - $DASHBOARDS_DATA_APP:/data_app/
      - $DASHBOARDS_DATA_CLEAN:/data_clean/
      - $DASHBOARDS_DATA_RAW:/data_raw/
      - $DASHBOARDS_RESULTS:/results/

      - $DASHBOARDS_JUNIT:/junit/
      - $DASHBOARDS_RSTUDIO/:/home/rstudio/

      - xtmp:/xtmp/
    environment:
      - COMPUTER=${COMPUTER:-noname}
      - PASSWORD=rstudio1
      - DISABLE_AUTH=true
```

Inside RStudio I type:

```
> Sys.getenv("PASSWORD")
[1] ""
> Sys.getenv("COMPUTER")
[1] ""
```

If I log into the terminal as root:

```
xxx@xxx:[xxx]: docker exec -it infrastructure_rstudio_1 bash
root@957fd8514387:/# echo $PASSWORD
rstudio1
root@957fd8514387:/# echo $COMPUTER
xxx
```

So the environmental variables make it into the docker container, but RStudio Server seems to strip them out. Any idea on how to make the environmental variables accessible internally?
