### ISSUE TITLE
Call R from nginx+php:fpm

### ISSUE THREAD

**Issue by mikldk** [rocker-org/rocker#453]
Thanks for your effort. I am not sure that I ask the right place, but I wasn't sure where to ask so now I try here (and cross my fingers):

I am new in the docker world. For fun, I am trying to make a webserver (nginx + PHP) where I can call R from PHP. 

I have a `docker-compose.yml` containing:

```
version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    r-base:
      image: rocker/r-base:latest
    php:
        image: php:fpm
        volumes:
            - ./app:/app
```

And `app/public/index.php` contains
```
<?php
$test = exec('R --vanilla --quiet --no-save -e "2+2;"');
var_dump($test);
```
As a result I get ` string(0) "" ` and at the console I get 

```
php_1    | sh: 1: R: not found
```

If I in `index.php` instead tries `exec('ls -l /usr/bin')` I don't see R. I am not really sure how to expose R for PHP.

Is this rocker related? Or do you have a suggestion for where I can ask this question?
