### ISSUE TITLE
TinyTex and Github Actions

### ISSUE THREAD

**Issue by alearrigo** [rocker-org/rocker#528]
Hi, 
I have a problem that I'm not exactly sure how to solve or investigate. 
I need to compile some quarto reports in pdf and I have all the scripts ready that run flawlessly on my pc.
I set up some Github actions but I have the following issues:

Below is a part of a YAML file that I use for a GitHub action:

````

on: 
  workflow_dispatch:


name: Test Run

run-name: Test Run


jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: 
      image: rocker/verse:latest
      
    steps:

    - name: Checkout private tools
      uses: actions/checkout@v3
      

    - name: check tex
      run: quarto tools info tinytex
      shell: bash

```

The issue is that the step in the job gives me:

{
  "name": "TinyTeX",
  "installed": false
}

and abort the process.

I can't pull your repo because I'm on apple silicon, so I've built an image with TinyTex installed and if I run the process in locale it gives me:

{
  "name": "TinyTeX",
  "installed": true,
  "version": "v2023.07.08",
  "directory": "/root/.TinyTeX",
  "bin-directory": "/root/.TinyTeX/bin/x86_64-linux",
  "configuration": {
    "status": "ok"
  }
}

But then again, I pushed to docker hub (alearrigo/r_quarto_tidyverse_git:v2) and when I use this image to build the container on GitHub I receive the same message of latex non-installed and If I run 'quarto tools info tinytex' I  receive:

{
  "name": "TinyTeX",
  "installed": false
}

How do I solve the problem to use your images on GHA?

Thanks!
